backend:
  name: git-gateway
  branch: main
  auth_type: implicit
  identity_url: https://mdexotic.com/.netlify/identity
  gateway_url: https://mdexotic.com/.netlify/git

media_folder: "static/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Страници"
    files:
      - file: "content/pages/index.md"
        label: "Начало"
        name: "home"
        fields:
          - {label: "SEO Title", name: "seo_title", widget: "string"}
          - {label: "SEO Description", name: "seo_description", widget: "text"}
          - {label: "Hero Заглавие", name: "hero_title", widget: "string"}
          - {label: "Hero Подзаглавие", name: "hero_subtitle", widget: "text"}
          - {label: "Hero Фон", name: "hero_bg", widget: "image"}