backend:
  name: git-gateway
  branch: main
  auth_type: implicit

media_folder: "static/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow

collections:
  - name: "raw"
    label: "Съдържание (RAW JSON)"
    files:
      - file: "content/site.json"
        label: "content/site.json"
        name: "content_site"
        format: "json"
        editor: { preview: false }
        fields:
          - { label: "JSON", name: "body", widget: "code", default_language: "json", output_code_only: true }

      - file: "content/prices.json"
        label: "content/prices.json"
        name: "content_prices"
        format: "json"
        editor: { preview: false }
        fields:
          - { label: "JSON", name: "body", widget: "code", default_language: "json", output_code_only: true }

      # ако сайтът чете копията в корена – редактираш и тях тук
      - file: "site.json"
        label: "site.json (root)"
        name: "root_site"
        format: "json"
        editor: { preview: false }
        fields:
          - { label: "JSON", name: "body", widget: "code", default_language: "json", output_code_only: true }

      - file: "prices.json"
        label: "prices.json (root)"
        name: "root_prices"
        format: "json"
        editor: { preview: false }
        fields:
          - { label: "JSON", name: "body", widget: "code", default_language: "json", output_code_only: true }
